apiVersion: apps/v1
kind: Deployment
metadata:
  name: WIki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WIki
  template:
    metadata:
      labels:
        app: WIki
    spec:
      containers:
        - name: WIki
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
