apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-svc
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: ${SERVER_PORT}
      targetPort: ${CONTAINER_PORT}
  type: ClusterIP