name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - master
  pull_request:
    branches:
      - dev
      - staging
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      id-token: write

      contents: read
    strategy:
      matrix:
        include:
          - environment: dev
            branch: dev
          - environment: staging
            branch: staging
          - environment: prod
            branch: master
    if: ${{ matrix.branch == github.ref_name }}

    steps:
      - name: Check branch and environment

        run: echo "Deploying to ${{ matrix.environment }} on branch ${{ matrix.branch }}"
      - name: Checkout code

        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::571600859033:role/GitHubActionsECRRole
          aws-region: us-east-2
          role-session-name: GitHubActionsSession

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and push Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/wiki:$IMAGE_TAG .
          docker push $ECR_REGISTRY/wiki:$IMAGE_TAG

      - name: Update image tag in variables.yaml
        run: |
          yq e ".image_tag = \"${{ github.sha }}\"" k8s/base/app/variables.yaml -i

      - name: Deploy to ${{ matrix.environment }}
        run: |
          cd k8s/overlays/${{ matrix.environment }}
          kustomize build . | kubectl apply -f - -n ${{ matrix.environment }}