name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - master
  pull_request:
    branches:
      - dev
      - staging
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    strategy:
      matrix:
        environment: [dev, staging, prod]
        branch: [dev, staging, prod]
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        run: echo "Deploying to ${{ matrix.environment }} on branch ${{ matrix.branch }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push Docker image
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/wiki:$IMAGE_TAG .
          docker push $ECR_REGISTRY/wiki:$IMAGE_TAG
      - name: Update image tag in variables.yaml
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        run: |
          yq e ".image_tag = \"${{ github.sha }}\"" k8s/base/app/variables.yaml -i
      - name: Deploy to ${{ matrix.environment }}
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        run: |
          cd k8s/overlays/${{ matrix.environment }}
          kustomize build . | kubectl apply -f - -n ${{ matrix.environment }}