name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - master
  pull_request:
    branches:
      - dev
      - staging
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
        branch: [dev, staging, master]
    steps:
      - name: Check branch and environment
        run: echo "Deploying to ${{ matrix.environment }} on branch ${{ matrix.branch }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAYKFQQ56M7FUCSEH7
          aws-secret-access-key: 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
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build and push Docker image
        id: build-image
        env:
          ECR_REGISTRY: 571600859033.dkr.ecr.us-east-2.amazonaws.com/wiki-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t 571600859033.dkr.ecr.us-east-2.amazonaws.com/wiki-repo/wiki:$IMAGE_TAG .
          docker push 571600859033.dkr.ecr.us-east-2.amazonaws.com/wiki-repo/wiki:$IMAGE_TAG
      - name: Update image tag in variables.yaml
        run: |
          yq e ".image_tag = \"${{ github.sha }}\"" k8s/base/app/variables.yaml -i
      - name: Deploy to ${{ matrix.environment }}
        run: |
          cd k8s/overlays/${{ matrix.environment }}
          kustomize build . | kubectl apply -f - -n ${{ matrix.environment }}